//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EjemploWS
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Persona", Namespace="http://tempuri.org/")]
    public partial class Persona : object
    {
        
        private int idField;
        
        private string CuilField;
        
        private string ApellidoYNombreField;
        
        private System.DateTime FechaNacimientoField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Cuil
        {
            get
            {
                return this.CuilField;
            }
            set
            {
                this.CuilField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ApellidoYNombre
        {
            get
            {
                return this.ApellidoYNombreField;
            }
            set
            {
                this.ApellidoYNombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.DateTime FechaNacimiento
        {
            get
            {
                return this.FechaNacimientoField;
            }
            set
            {
                this.FechaNacimientoField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EjemploWS.EjemploSoap")]
    public interface EjemploSoap
    {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento nueva del espacio de nombres http://tempuri.org/ no está marcado para convertirse en valor nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegistroPersona", ReplyAction="*")]
        EjemploWS.RegistroPersonaResponse RegistroPersona(EjemploWS.RegistroPersonaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegistroPersona", ReplyAction="*")]
        System.Threading.Tasks.Task<EjemploWS.RegistroPersonaResponse> RegistroPersonaAsync(EjemploWS.RegistroPersonaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ApellidoYNombre del espacio de nombres http://tempuri.org/ no está marcado para convertirse en valor nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerPersona", ReplyAction="*")]
        EjemploWS.ObtenerPersonaResponse ObtenerPersona(EjemploWS.ObtenerPersonaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerPersona", ReplyAction="*")]
        System.Threading.Tasks.Task<EjemploWS.ObtenerPersonaResponse> ObtenerPersonaAsync(EjemploWS.ObtenerPersonaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento nueva del espacio de nombres http://tempuri.org/ no está marcado para convertirse en valor nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ModificarPersona", ReplyAction="*")]
        EjemploWS.ModificarPersonaResponse ModificarPersona(EjemploWS.ModificarPersonaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ModificarPersona", ReplyAction="*")]
        System.Threading.Tasks.Task<EjemploWS.ModificarPersonaResponse> ModificarPersonaAsync(EjemploWS.ModificarPersonaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento nueva del espacio de nombres http://tempuri.org/ no está marcado para convertirse en valor nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EliminarPersona", ReplyAction="*")]
        EjemploWS.EliminarPersonaResponse EliminarPersona(EjemploWS.EliminarPersonaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EliminarPersona", ReplyAction="*")]
        System.Threading.Tasks.Task<EjemploWS.EliminarPersonaResponse> EliminarPersonaAsync(EjemploWS.EliminarPersonaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegistroPersonaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegistroPersona", Namespace="http://tempuri.org/", Order=0)]
        public EjemploWS.RegistroPersonaRequestBody Body;
        
        public RegistroPersonaRequest()
        {
        }
        
        public RegistroPersonaRequest(EjemploWS.RegistroPersonaRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegistroPersonaRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public EjemploWS.Persona nueva;
        
        public RegistroPersonaRequestBody()
        {
        }
        
        public RegistroPersonaRequestBody(EjemploWS.Persona nueva)
        {
            this.nueva = nueva;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegistroPersonaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegistroPersonaResponse", Namespace="http://tempuri.org/", Order=0)]
        public EjemploWS.RegistroPersonaResponseBody Body;
        
        public RegistroPersonaResponse()
        {
        }
        
        public RegistroPersonaResponse(EjemploWS.RegistroPersonaResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegistroPersonaResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public EjemploWS.Persona RegistroPersonaResult;
        
        public RegistroPersonaResponseBody()
        {
        }
        
        public RegistroPersonaResponseBody(EjemploWS.Persona RegistroPersonaResult)
        {
            this.RegistroPersonaResult = RegistroPersonaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerPersonaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerPersona", Namespace="http://tempuri.org/", Order=0)]
        public EjemploWS.ObtenerPersonaRequestBody Body;
        
        public ObtenerPersonaRequest()
        {
        }
        
        public ObtenerPersonaRequest(EjemploWS.ObtenerPersonaRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerPersonaRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ApellidoYNombre;
        
        public ObtenerPersonaRequestBody()
        {
        }
        
        public ObtenerPersonaRequestBody(string ApellidoYNombre)
        {
            this.ApellidoYNombre = ApellidoYNombre;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerPersonaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerPersonaResponse", Namespace="http://tempuri.org/", Order=0)]
        public EjemploWS.ObtenerPersonaResponseBody Body;
        
        public ObtenerPersonaResponse()
        {
        }
        
        public ObtenerPersonaResponse(EjemploWS.ObtenerPersonaResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerPersonaResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public EjemploWS.Persona[] ObtenerPersonaResult;
        
        public ObtenerPersonaResponseBody()
        {
        }
        
        public ObtenerPersonaResponseBody(EjemploWS.Persona[] ObtenerPersonaResult)
        {
            this.ObtenerPersonaResult = ObtenerPersonaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ModificarPersonaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ModificarPersona", Namespace="http://tempuri.org/", Order=0)]
        public EjemploWS.ModificarPersonaRequestBody Body;
        
        public ModificarPersonaRequest()
        {
        }
        
        public ModificarPersonaRequest(EjemploWS.ModificarPersonaRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ModificarPersonaRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public EjemploWS.Persona nueva;
        
        public ModificarPersonaRequestBody()
        {
        }
        
        public ModificarPersonaRequestBody(EjemploWS.Persona nueva)
        {
            this.nueva = nueva;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ModificarPersonaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ModificarPersonaResponse", Namespace="http://tempuri.org/", Order=0)]
        public EjemploWS.ModificarPersonaResponseBody Body;
        
        public ModificarPersonaResponse()
        {
        }
        
        public ModificarPersonaResponse(EjemploWS.ModificarPersonaResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ModificarPersonaResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public EjemploWS.Persona ModificarPersonaResult;
        
        public ModificarPersonaResponseBody()
        {
        }
        
        public ModificarPersonaResponseBody(EjemploWS.Persona ModificarPersonaResult)
        {
            this.ModificarPersonaResult = ModificarPersonaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EliminarPersonaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EliminarPersona", Namespace="http://tempuri.org/", Order=0)]
        public EjemploWS.EliminarPersonaRequestBody Body;
        
        public EliminarPersonaRequest()
        {
        }
        
        public EliminarPersonaRequest(EjemploWS.EliminarPersonaRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EliminarPersonaRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public EjemploWS.Persona nueva;
        
        public EliminarPersonaRequestBody()
        {
        }
        
        public EliminarPersonaRequestBody(EjemploWS.Persona nueva)
        {
            this.nueva = nueva;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EliminarPersonaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EliminarPersonaResponse", Namespace="http://tempuri.org/", Order=0)]
        public EjemploWS.EliminarPersonaResponseBody Body;
        
        public EliminarPersonaResponse()
        {
        }
        
        public EliminarPersonaResponse(EjemploWS.EliminarPersonaResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EliminarPersonaResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public EjemploWS.Persona EliminarPersonaResult;
        
        public EliminarPersonaResponseBody()
        {
        }
        
        public EliminarPersonaResponseBody(EjemploWS.Persona EliminarPersonaResult)
        {
            this.EliminarPersonaResult = EliminarPersonaResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface EjemploSoapChannel : EjemploWS.EjemploSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class EjemploSoapClient : System.ServiceModel.ClientBase<EjemploWS.EjemploSoap>, EjemploWS.EjemploSoap
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public EjemploSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(EjemploSoapClient.GetBindingForEndpoint(endpointConfiguration), EjemploSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EjemploSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(EjemploSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EjemploSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(EjemploSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EjemploSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EjemploWS.RegistroPersonaResponse EjemploWS.EjemploSoap.RegistroPersona(EjemploWS.RegistroPersonaRequest request)
        {
            return base.Channel.RegistroPersona(request);
        }
        
        public EjemploWS.Persona RegistroPersona(EjemploWS.Persona nueva)
        {
            EjemploWS.RegistroPersonaRequest inValue = new EjemploWS.RegistroPersonaRequest();
            inValue.Body = new EjemploWS.RegistroPersonaRequestBody();
            inValue.Body.nueva = nueva;
            EjemploWS.RegistroPersonaResponse retVal = ((EjemploWS.EjemploSoap)(this)).RegistroPersona(inValue);
            return retVal.Body.RegistroPersonaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EjemploWS.RegistroPersonaResponse> EjemploWS.EjemploSoap.RegistroPersonaAsync(EjemploWS.RegistroPersonaRequest request)
        {
            return base.Channel.RegistroPersonaAsync(request);
        }
        
        public System.Threading.Tasks.Task<EjemploWS.RegistroPersonaResponse> RegistroPersonaAsync(EjemploWS.Persona nueva)
        {
            EjemploWS.RegistroPersonaRequest inValue = new EjemploWS.RegistroPersonaRequest();
            inValue.Body = new EjemploWS.RegistroPersonaRequestBody();
            inValue.Body.nueva = nueva;
            return ((EjemploWS.EjemploSoap)(this)).RegistroPersonaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EjemploWS.ObtenerPersonaResponse EjemploWS.EjemploSoap.ObtenerPersona(EjemploWS.ObtenerPersonaRequest request)
        {
            return base.Channel.ObtenerPersona(request);
        }
        
        public EjemploWS.Persona[] ObtenerPersona(string ApellidoYNombre)
        {
            EjemploWS.ObtenerPersonaRequest inValue = new EjemploWS.ObtenerPersonaRequest();
            inValue.Body = new EjemploWS.ObtenerPersonaRequestBody();
            inValue.Body.ApellidoYNombre = ApellidoYNombre;
            EjemploWS.ObtenerPersonaResponse retVal = ((EjemploWS.EjemploSoap)(this)).ObtenerPersona(inValue);
            return retVal.Body.ObtenerPersonaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EjemploWS.ObtenerPersonaResponse> EjemploWS.EjemploSoap.ObtenerPersonaAsync(EjemploWS.ObtenerPersonaRequest request)
        {
            return base.Channel.ObtenerPersonaAsync(request);
        }
        
        public System.Threading.Tasks.Task<EjemploWS.ObtenerPersonaResponse> ObtenerPersonaAsync(string ApellidoYNombre)
        {
            EjemploWS.ObtenerPersonaRequest inValue = new EjemploWS.ObtenerPersonaRequest();
            inValue.Body = new EjemploWS.ObtenerPersonaRequestBody();
            inValue.Body.ApellidoYNombre = ApellidoYNombre;
            return ((EjemploWS.EjemploSoap)(this)).ObtenerPersonaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EjemploWS.ModificarPersonaResponse EjemploWS.EjemploSoap.ModificarPersona(EjemploWS.ModificarPersonaRequest request)
        {
            return base.Channel.ModificarPersona(request);
        }
        
        public EjemploWS.Persona ModificarPersona(EjemploWS.Persona nueva)
        {
            EjemploWS.ModificarPersonaRequest inValue = new EjemploWS.ModificarPersonaRequest();
            inValue.Body = new EjemploWS.ModificarPersonaRequestBody();
            inValue.Body.nueva = nueva;
            EjemploWS.ModificarPersonaResponse retVal = ((EjemploWS.EjemploSoap)(this)).ModificarPersona(inValue);
            return retVal.Body.ModificarPersonaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EjemploWS.ModificarPersonaResponse> EjemploWS.EjemploSoap.ModificarPersonaAsync(EjemploWS.ModificarPersonaRequest request)
        {
            return base.Channel.ModificarPersonaAsync(request);
        }
        
        public System.Threading.Tasks.Task<EjemploWS.ModificarPersonaResponse> ModificarPersonaAsync(EjemploWS.Persona nueva)
        {
            EjemploWS.ModificarPersonaRequest inValue = new EjemploWS.ModificarPersonaRequest();
            inValue.Body = new EjemploWS.ModificarPersonaRequestBody();
            inValue.Body.nueva = nueva;
            return ((EjemploWS.EjemploSoap)(this)).ModificarPersonaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EjemploWS.EliminarPersonaResponse EjemploWS.EjemploSoap.EliminarPersona(EjemploWS.EliminarPersonaRequest request)
        {
            return base.Channel.EliminarPersona(request);
        }
        
        public EjemploWS.Persona EliminarPersona(EjemploWS.Persona nueva)
        {
            EjemploWS.EliminarPersonaRequest inValue = new EjemploWS.EliminarPersonaRequest();
            inValue.Body = new EjemploWS.EliminarPersonaRequestBody();
            inValue.Body.nueva = nueva;
            EjemploWS.EliminarPersonaResponse retVal = ((EjemploWS.EjemploSoap)(this)).EliminarPersona(inValue);
            return retVal.Body.EliminarPersonaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EjemploWS.EliminarPersonaResponse> EjemploWS.EjemploSoap.EliminarPersonaAsync(EjemploWS.EliminarPersonaRequest request)
        {
            return base.Channel.EliminarPersonaAsync(request);
        }
        
        public System.Threading.Tasks.Task<EjemploWS.EliminarPersonaResponse> EliminarPersonaAsync(EjemploWS.Persona nueva)
        {
            EjemploWS.EliminarPersonaRequest inValue = new EjemploWS.EliminarPersonaRequest();
            inValue.Body = new EjemploWS.EliminarPersonaRequestBody();
            inValue.Body.nueva = nueva;
            return ((EjemploWS.EjemploSoap)(this)).EliminarPersonaAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.EjemploSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.EjemploSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.EjemploSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:54668/Ejemplo.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.EjemploSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:54668/Ejemplo.asmx");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            EjemploSoap,
            
            EjemploSoap12,
        }
    }
}
